# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
- name: CICD_VarGroup
  value: true

pool:
  vmImage: 'windows-latest'
stages:
  - stage: Build
    displayName: Build Package
    jobs: 
    - job: BuildPackage

      steps:    
      - task: UiPathPack@2
        inputs:
          versionType: 'AutoVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'Test_Orch_Devopps'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

  - stage: Run Process Flow
    displayName: Run Process
    condition: succeeded()
    jobs: 
    - job: RunPackage

       
      

  - stage: TestDEV
    displayName:  Test Cases
    condition: succeeded()
    jobs:
      - job: TestDEV

        steps:
          - task: UiPathTest@2
            inputs:
              testTarget: 'TestSet'
              orchestratorConnection: 'Test_Orch_Devopps'
              testSet: 'test1'
              folderName: 'Training'

  - stage: DeployDEV
    displayName: Deploy build artifact to DEV

    condition: succeeded()
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to DEV Orchestrator

        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: 'UAT Connection'
                packagesPath: '$(Build.ArtifactStagingDirectory)\SIR'
                folderName: 'Shared'
                entryPoints: 'Main.xaml'
                traceLevel: 'Information'